name: Build

on: [ workflow_dispatch, pull_request ]

jobs:
  Android:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false) }}
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - uses: burrunan/gradle-cache-action@v1
        name: Test
        with:
          arguments: :android:app:assemble

  KMP:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false) }}
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - uses: burrunan/gradle-cache-action@v1
        name: Test
        with:
          arguments: :kmp:shared:assemble

  iOS:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false) }}
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

#      - name: Set up cocoapods
#        uses: maxim-lobanov/setup-cocoapods@v1
#        with:
#          podfile-path: ios/Podfile.lock

      - run: xcodebuild -workspace ios/TimiIOS.xcworkspace -configuration Debug -scheme TimiIOS -sdk iphoneos -destination name='iPhone 12' build

#      - uses: burrunan/gradle-cache-action@v1
#        name: Test
#        with:
#          arguments: :kmp:app:compileKotlinIosX64
#
#      - name: Install Dependencies
#        run: |
#          cd ios
#          pod install --verbose
#
#      - name: Build
#        uses: sersoft-gmbh/xcodebuild-action@v2
#        with:
#          workspace: ios/TimiIOS.xcworkspace
#          scheme: TimiIOS
#          destination: name=iPhone 12
#          sdk: iphoneos
#          configuration: Debug
#          action: build
