name: Linting check

on: [ pull_request ]

jobs:
  check:
    runs-on: ubuntu-latest

    name: Run ktlint on the project
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: ktlintCheck
