name: Linting check

on: [ workflow_dispatch, pull_request ]

jobs:
  check:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false) }}
    runs-on: ubuntu-latest

    name: Run ktlint on the project
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: ktlintCheck
