name: Linting check

on: [ push ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#      - uses: eskatos/gradle-command-action@v1
#        with:
#          arguments: ktlintCheck
